//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Activity
    {
        public System.Guid Id { get; set; }
        public System.Guid RequestId { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Result { get; set; }
        public Nullable<System.Guid> PersonelId { get; set; }
        public Nullable<System.Guid> ActivityTypeId { get; set; }
    
        public virtual ActivitiesTypesDictionary ActivitiesTypesDictionary { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Request Request { get; set; }
    }
}
