//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public string Descr { get; set; }
        public string Status { get; set; }
        public string Result { get; set; }
        public int Id { get; set; }
        public int ReqId { get; set; }
        public string Type { get; set; }
        public Nullable<int> WorkerId { get; set; }
    
        public virtual ActivitiesTypesDictionary ActivitiesTypesDictionary { get; set; }
        public virtual Request Request { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
