//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string UName { get; set; }
        public string Pass { get; set; }
        public int WorkerId { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
